CLASS /ITETR/CL_INC0100_MPC_EXT DEFINITION
PUBLIC
INHERITING FROM /ITETR/CL_INC0100_MPC
CREATE PUBLIC .

PUBLIC SECTION.

*TYPES: BEGIN OF TS_DE_INVOICEDETAIL.
*  INCLUDE TYPE ts_invoicedetails.
*  TYPES:
*  NavInvoiceDetailOne TYPE STANDARD TABLE OF ts_invoicedetailone WITH DEFAULT KEY,
*  NavInvoiceDetailTwo TYPE STANDARD TABLE OF ts_invoicedetailtwo WITH DEFAULT KEY,
*END OF TS_DE_INVOICEDETAIL.

METHODS DEFINE
REDEFINITION .
protected section.
private section.
ENDCLASS.



CLASS /ITETR/CL_INC0100_MPC_EXT IMPLEMENTATION.


  method DEFINE.

  endmethod.
ENDCLASS.